name: SonarQube (SonarCloud)

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze with SonarCloud
    runs-on: ubuntu-latest
    env:
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for SonarCloud to detect all code history

      - name: Set up Java (if needed)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Adjust this version to match your project's needs

      - name: Install Build Wrapper
        uses: SonarSource/sonarqube-scan-action/install-build-wrapper@v5

      - name: Try build systems in a loop
        run: |
          # Loop through possible build commands
          for build_command in "make" "mvn clean install" "./gradlew build" "npm install && npm run build"; do
            echo "Attempting to run: $build_command"
            if $build_command; then
              echo "Build succeeded with: $build_command"
              build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} $build_command
              break
            else
              echo "Build failed with: $build_command"
            fi
          done

      - name: SonarQube Scan with properties file
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            --define sonar.cfamily.compile-commands="${{ env.BUILD_WRAPPER_OUT_DIR }}/compile_commands.json"

      - name: Upload build wrapper output (optional)
        uses: actions/upload-artifact@v4
        with:
          name: build-wrapper-output
          path: ${{ env.BUILD_WRAPPER_OUT_DIR }}
